tor_home:
    path:     /
    defaults: { _controller: TorBundle:Default:index }
    options:
            expose: true


tor_calendar:
    path:     /home
    defaults: { _controller: TorBundle:Tor:index }
    options:
            expose: true

tor_rezerwuj:
    path:     /rezerwuj/{date}
    defaults: { _controller: TorBundle:Tor:rezerwuj }
    options:
                expose: true

tor_instructors:
    path:     /instruktorzy/
    defaults: { _controller: TorBundle:Tor:listInstructors }
    options:
                expose: true

tor_users:
    path:    /admin
    defaults: {_controller: TorBundle:Default:listUsers}

tor_zmien:
    path:    /admin/zmien/{id}/{action}/{role}
    defaults: {_controller: TorBundle:Default:zmien}

tor_zablokuj:
    path:    /admin/zablokuj/{id}/{action}
    defaults: {_controller: TorBundle:Default:zablokuj}
