tor_records:
    resource: "@TorBundle/Resources/config/routing/records.yml"
    prefix:   admin/records

tor_records_user:
    path:     /recordsuser
    defaults: { _controller: "TorBundle:Records:indexUser" }

tor_home:
    path:     /
    defaults: { _controller: TorBundle:Tor:home }
    options:
            expose: true


tor_calendar:
    path:     /home
    defaults: { _controller: TorBundle:Tor:index }
    options:
            expose: true

tor_rezerwuj:
    path:     /rezerwuj/{date}/{param}
    defaults: { _controller: TorBundle:Tor:rezerwuj }
    options:
                expose: true

tor_instructorCalendar:
    path:     /instruktor/{id}
    defaults: { _controller: TorBundle:Tor:instructorCalendar }
    options:
                expose: true

tor_instructors:
    path:     /instruktorzy/
    defaults: { _controller: TorBundle:Tor:listInstructors }
    options:
                expose: true

tor_panel:
    path:    admin/panel
    defaults: {_controller: TorBundle:Default:panel}

tor_users:
    path:    admin/users
    defaults: {_controller: TorBundle:Default:listUsers}

tor_zmien:
    path:    /admin/zmien/{id}/{action}/{role}
    defaults: {_controller: TorBundle:Default:zmien}

tor_zablokuj:
    path:    /admin/zablokuj/{id}/{action}
    defaults: {_controller: TorBundle:Default:zablokuj}
